### ISSUE TITLE
Error when restoring settings

### ISSUE THREAD

**Issue by gillesoorts** [BenjV/SYNO-packages#1]
Hey,

First off all, thank you very much for creating a DSM 6 package, I finally did the update today now that my favourite package supports version 6!

However I encountered an error when trying to restore the settings from the previous Synology package. I first entered the path for the backup/restore setting, saved it and tried the restore function. That's when I got this page, had to stop the Synology package and it won't restart anymore.

I also did give the autosub user the necessary read/write permissions, so that shouldn't be the problem.

System information:

Synology DS413
Synology DSM 6.0.2-8451 Update 7
Autosub Synology Package v1.2 (although the downloaded file name, and the GUI during installation still says 1.0) 

Kind regards,
Gilles
![screen shot 2017-01-08 at 16 27 12](https://cloud.githubusercontent.com/assets/17709900/21750993/10a965bc-d5c0-11e6-925c-764e9f215327.png)

**Comment by BenjV** [comment]
Apperently your missing some files.
Maybe uninstall the package, download a fresh copy from GitHub and install it again.

**Comment by gillesoorts** [comment]
I had to re-download and reinstall it, because I couldn't get it to work otherwise. Had it running for the last day without problems (I entered all settings manually). As soon as a tried to restore settings just now, I got the same problem. Could these files be missing from the Synology package?

**Comment by BenjV** [comment]
No the package is working fine on my own Syno and on lots of other peoples machine.

Do you use the correct python package?
You need the one from the SynoCommunity.

**Comment by gillesoorts** [comment]
I have version 2.7.13-16 installed, developed by Diaoul and published by SynoCommunity.

I just noticed SynoCommunity has another package called Python3. Should I switch to this one?

**Comment by BenjV** [comment]
No autosub does not work with Python 3
