### ISSUE TITLE
Can't update v1.1 syno package to the python 3 version

### ISSUE THREAD

**Issue by spoelly** [BenjV/SYNO-packages#12]
I wanted to install the pyton 3 version over my current setup (v1.1) but the installer won't let me because it says you can't update to a lower version

What can is do?

**Comment by BenjV** [comment]
Of course not.
You cannot upgrade a package running on python 2 to a python 3 package.

Make a backup from within SickChill.
Remove the old SickChill package.
Make sure you have installed Python3 from the SynoCommunity.
Install the new package.
Restore the backup from within SickChill

**Comment by spoelly** [comment]
Ow my bad I wasn't thinking straight. Thanks for the advise! Will wait until the related issue is fixed!

**Comment by spoelly** [comment]
The new package is working perfectly, thanks!
