### ISSUE TITLE
Cant change http port

### ISSUE THREAD

**Issue by kungktd** [BenjV/SYNO-packages#15]
Is your version locked to port 8899? I have tried to change it but every time I restart its back to 8899. All other config changes are ok  after a reboot.

UPDATE, I’m talking about your SickChill...

**Comment by BenjV** [comment]
You are correct.
The Synology package center is using the port for DSM purposes and changing the port will mess-up DSM.
It has to a fixed a port within the package.
The policy is to prevent changing the port to everything keep working as it should.
And my packages complies to that to ensure the correct behavior.

**Comment by kungktd** [comment]
Ok. I was using SickChill via sickbeard-custom from SynoCommunity until now and there I could use whatever port I wanted.
No biggie since I didn’t use 8899 anyway. But I have more major issues but I will create a new issue for it.

Thanks for answering!
