### ISSUE TITLE
Restore problem

### ISSUE THREAD

**Issue by hugo-leij** [BenjV/SYNO-packages#16]
He,

I have performed the update but I cannot restore the backup. The log also does not mention anything.

If I transfer the config manually, it will be overwritten by a new config if i restart sickchill. If I change something in the config with 'vi' and I restart sickchill, the changes are also gone.

![image](https://user-images.githubusercontent.com/10241984/94734772-fca42f80-0369-11eb-817d-423c776d6655.png)

**Comment by BenjV** [comment]
No idea, you should ask the developers of SickChill.
