### ISSUE TITLE
Verkeerde gebruiker in sickarge spk?

### ISSUE THREAD

**Issue by neoatomic** [BenjV/SYNO-packages#2]
@BenjV Was even aan het proberen het Sickrage paket aan te passen voor Medusa, en daarbij viel me op dat in `scripts/postupgrade` de gebruiker verkeerd lijkt : `USER="autosub" `

(Overigens nog niet gelukt om dat Medusa pakket aan het draaien te krijgen. Wil niet starten...)

Edit: https://github.com/neoatomic/SYNO-packages/raw/3153cf507c00b3cab0f1fdbd38cbb752ddffc41d/Medusa%20DSM%206%20noarch%20V1.0.spk

```
#!/bin/sh

SC_GROUP="sc-media"
SC_GROUP_DESC="Media related group"
USER="autosub"

    # Create syno group with the user in it (Does nothing when syno group already exists) 
synogroup --add ${SC_GROUP} ${USER} > /dev/null
if [ $? -eq 0 ];
    then
		synogroup --descset ${SC_GROUP} "${SC_GROUP_DESC}" ;
	else
		MEMBERS="$(synogroup --get ${SC_GROUP} | grep '^[0-9]' | sed 's/.*\[\([^]]*\)].*/\1/' | tr '\n' ' ')";
			# The member command needs al users on the command line so we add the user to the list we just found
		if [[ ${MEMBERS} != *${USER}* ]] ;
			then
				synogroup --member sc-media ${MEMBERS}${USER};
				synogroup --rebuild all;
		fi	
fi
synogroup --rebuild all
exit 0
```

**Comment by BenjV** [comment]
Ja is een foutje, moet uiteraard sickrage zijn.
Ik zal het aanpassen.
Heb als basis uiteraard het package voor autosub gebruikt.

Op zich geen probleem want het package wil je eigenlijk nooit updaten, aangezien Sickrage zichzelf update (net als autosub).

Ik zal morgen wel even naar je medusa package kijken of ik zie wat er mis gaat.

**Comment by BenjV** [comment]
Heb niet erg veel tijd gehad om er naar te kijken want iemand had een onverklaarbaar probleem met autosub.
Maar ben er wel achter dat jouw medusa package geen python virtual environment aanmaakt en het start-stop script gaat er wel vanuit dat zo'n environment er is.
Morgen eens verder puzzelen waarom die /env niet wordt aangemaakt.

**Comment by neoatomic** [comment]
Bedankt dat je er even naar gekeken hebt. ;)
Kreeg het verzoek van een bekende om zo'n pakket in elkaar te knutsellen. Maar zonder succes helaas...
Mocht je de oorzaak alsnog vinden dan alvast mijn dank.  :+1:
