### ISSUE TITLE
Install refused with Synology Python3

### ISSUE THREAD

**Issue by scott451** [BenjV/SYNO-packages#22]
Hello,

I recently installed the 'official' Synology package for Python3, so I am now at v3.8.  When I install the Medusa package the installer says it cannot find Python3.

I wonder if it is not specifically looking for the SynoCommunity Python3 package (v3.7). Thanks for your insight,

- Scott

**Comment by BenjV** [comment]
Yes it is.
You need as I already stated Python3 from the SynoCommunity.
