### ISSUE TITLE
Medusa on Synology won´t start after last update

### ISSUE THREAD

**Issue by MrFearmanDK** [BenjV/SYNO-packages#25]
Got message that Medusa was updated "Medusa Updated To Commit#: 2b874c2c6a3c33d653eec6e50598a194627a6f76"

But now it won´t start again "Failed to run the package service"

My Synology is running DSM 6.2.3-25426 Update 3

**Comment by BenjV** [comment]
Try to reboot your Nas

**Comment by MrFearmanDK** [comment]
Sorry, but same issue as before reboot

**Comment by BenjV** [comment]
I have no Idea.
I just update my Medusa to the same version without any problem.
You can try to install it again, it should keep the config and database intact.

If you want to be very sure you could save the config and database first.
That are these files:
/var/packages/medusa/target/var/main.db
/var/packages/medusa/target/var/config.ini
/var/packages/medusa/target/var/cache.db

**Comment by MrFearmanDK** [comment]
i copied the files you listed (SSH), installed Medusa 1.1 Python 3 noarch.spk and Medusa started, but now it is totally clean, no shows and no configuration.
I then tried copying the files back to the folder, but even though i do not get any error, the folder var/packages/medusa/target/var/ remains empty....
You have any clue what is happening?

**Comment by MrFearmanDK** [comment]
Does Medusa make a backup before updating??

**Comment by MrFearmanDK** [comment]
I tried rebooting my nas again and now everything is back to normal, found out that the version i was running was Medusa 1.0 Python 3 noarch.spk, do not know if this was the issue.

But where do Medusa save the backup files before updating?

**Comment by BenjV** [comment]
The back Medusa makes is here:
/var/packages/medusa/target/var/backup/
It is a zip file.

But you have all the files you need.
Most likely they ar now owned by the wrong user.
Try this command to fix that:

> chown -R sc-medusa:sc-medusa /var/packages/medusa/target/var/*

**Comment by MrFearmanDK** [comment]
Everything is up and running perfectly, thank you so much for your quick responce and help in this matter ;)
