### ISSUE TITLE
Updating to Medusa 1.3 and lost everything in Medusa

### ISSUE THREAD

**Issue by Teryon** [BenjV/SYNO-packages#27]
Hi,
I've updated manually to Medusa 1.3 in Synology package center , and now I don't have anything in my Medusa.
Is there a way to recover ?

Take care.

Tery.

**Comment by Teryon** [comment]
It seams that the database upgrade failed
How to startr it again ?

**Comment by BenjV** [comment]
If you did a backup from within medusa before you did the update then you could simply restore that backup.
If not you have to start fresh I guess.

**Comment by Teryon** [comment]
OK I've restored an old backup and updated everything.
I will teach me to backup whatever the situation.
