### ISSUE TITLE
User Account sickrage is running under

### ISSUE THREAD

**Issue by arejaytee** [BenjV/SYNO-packages#3]
What account is sickrage trying to run as? I am getting  error 13 : Permission denied when trying to move files from the Post Processing folder.. I have even given the guest user read/write access to try and get around it/

**Comment by arejaytee** [comment]
2017-10-05 11:18:28 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /volume1/Bitorrent/Completed completed
2017-10-05 11:18:28 INFO POSTPROCESSOR-AUTO :: /volume1/Bitorrent/Completed/file.mkv : Processing failed: Unable to move the files to their new home
2017-10-05 11:18:28 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2017-10-05 11:18:28 WARNING POSTPROCESSOR-AUTO :: Processing Failed
2017-10-05 11:18:28 WARNING POSTPROCESSOR-AUTO :: Processing failed for /volume1/Bitorrent/Completed/file.mkv: Unable to move the files to their new home
AA IOError: [Errno 13] Permission denied: "/volume1/Television/File.mkv"
AA with open(dst, 'wb') as fdst:
AA File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
AA copyfile(src, dst)
AA File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
AA copy2(src, real_dst)
AA File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
AA result = function(*[ss(x) if isinstance(x, six.string_types) else x for x in args], **kwargs)
AA File "/volume1/@appstore/sickrage/var/sickrage/helper/encoding.py", line 43, in ek
AA ek(shutil.move, srcFile, destFile)
AA File "/volume1/@appstore/sickrage/var/sickbeard/helpers.py", line 402, in moveFile
AA helpers.moveFile(cur_file_path, new_file_path)
AA File "/volume1/@appstore/sickrage/var/sickbeard/postProcessor.py", line 373, in _int_move

**Comment by BenjV** [comment]
If you have used my package then you can add permissions via the group "sc-media".
Package for DSM 6 run as a hidden user, so you have to give write permissions to the target folders via the group priviliges.

**Comment by arejaytee** [comment]
Thanks will give that a try and let you know

**Comment by arejaytee** [comment]
Gave permissions to the folder for the sc-media group which 80% worked, some folders created by the original sickrage user didn't inherited permissions so had to adjust them manually and then it worked.
