### ISSUE TITLE
Unable to connect to Transmission

### ISSUE THREAD

**Issue by teocasse** [BenjV/SYNO-packages#30]
Hi, first of all thank you for the great work on this package!

I've been using the Sickbeard Custom package with Sickchill for years now, but the performance has been increasingly worse and there are no updates on Python 2 anymore, so I've decided to pull the trigger and install Medusa on Python 3 from scratch (without restoring from backup to be safe, i.e. setting everything manually).

Installation went smoothly and the UI is very familiar yet much faster! However, there is an issue that is preventing me from switching off the old Sickchill. For some reason, I cannot set Transmission correctly as download client. For Transmission I am using the SynoCommunity package with standard port 9091, and in Medusa I am entering the exact same settings I have in Sickchill. However, clicking on "Test Connection" leads to a failure ("Unable to connect to Transmission"), while the same settings work on the old Sickbeard Custom. 

I honestly don't know why it should be due to the Medusa package, but I'm at a loss at what's happening and it's strange that the same settings work on the old app but not for this one.

**Comment by BenjV** [comment]
There wa a  issue with medusa and transmission.
Did you check within medusa if there is a new version, because I though it was fixed but maybe it is still in development

**Comment by teocasse** [comment]
I had checked and I am on the latest release 0.15.2, but I wasn't aware of the previous issues... I'll go over there and check if it has been fixed and released. At this point this is the most likely explanation...

**Comment by teocasse** [comment]
Found the confirmation here: https://github.com/pymedusa/Medusa/issues/9619

It's the same issue I'm having. It should be fixed on the develop branch, but very likely it hasn't been merged to master yet. Closing the issue as it has nothing to do with this package as suspected. Thanks for the pointer!
