### ISSUE TITLE
Branch Change Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [BenjV/SYNO-packages#40]
Good Day,

So i am trying to update this to Develop so i can do some testing and when i check out i am getting the below error:

`2022-01-14 10:24:19 WARNING  APIv2-Thread_0 :: [1405fbb] Couldn't determine current branch or current branch master doesn't match desired branch develop.
Checkout the desired branch or try again later.`

Is there a way i can do this via Synology SSH and if so how do i do this please.

Thanks

**Comment by BenjV** [comment]
There is no way to do this as far as I know.
The package installs a clone of the Master repositary, so that's the only one you can use.
It is not a git development environment.

I would suggest to use a PC to create a test environment.

**Comment by HPMSGEN8** [comment]
Hi @BenjV 

I managed to get this to go to DEV, With some copy and paste and overwrite folders. 

But thank.
