### ISSUE TITLE
Medusa - Failed to run package service - DMS 6

### ISSUE THREAD

**Issue by PyggieOp** [BenjV/SYNO-packages#41]
Hi BenjV,

first of all thanks a million for your work over the past years. I have always been able to use your packages easily. Until now :(

Medusa wouldn't start anymore after an in-app upgrade. I decided to uninstall the package (via Package Center). Then I went to your repository, downloaded "Medusa 1.7 Python 3 noarch.spk" and installed it via the "Manual install" option in Package Center.

The installation seems to complete, but then I keep getting the message "failed to run package service". Tried this several times now (in the hope it suddenly would work...) but without luck.

In other post you keep reminding about having Python 3 installed. I tried several, but have both 3.10 from SynoCommunity and the Python 3 package from Synology installed. And as the title says: I run on DSM 6 (latest updates installed)

Medusa log attached - if anything is needed, I am happy to provide it.
Thanks in advance for any help :)

[medusa.log](https://github.com/BenjV/SYNO-packages/files/8927860/medusa.log)

**Comment by BenjV** [comment]
From your log is can see there is a problem with ffprobe, which is a part of ffmpeg.
I assume you installed ffmpeg from the SynoCommunity and a issue about ffmpeg is reported there:
see:

> https://github.com/SynoCommunity/spksrc/issues/5314


Try to remove the use of ffmprobe in the config file, which can be found here:
/var/packages/medusa/target/var/config.ini
look for:

> [ffmpeg]
> ffmpeg_check_streams = 1
> 
And change it in:

> [ffmpeg]
> ffmpeg_check_streams = 0

**Comment by PyggieOp** [comment]
Hi BenjV,

thanks - The lines you mention weren't present in the Medusa config.ini. I did add it manually (with 0 value) and tried starting the package. Same issue....

**config.ini**
[General]
web_port = 8897

[ffmpeg]
ffmpeg_check_streams = 0

Uninstalled ffmpeg and tried running Medusa, and now it works just fine.
For now I will run it without ffmpeg - hopefully the team can fix that bug.

[medusa_package.log](https://github.com/BenjV/SYNO-packages/files/8933093/medusa_package.log)

Great help!
Dank je wel

**Comment by BenjV** [comment]
Apparently Medusa always test ffprobe when present and because the version of ffprobe from the SynoCommunity has a problem it fails.
So removing it fixed the problem.
On my Nas this problem is not present so it is only on specific models a problem.
