### ISSUE TITLE
DSM 6 -> DSM 7

### ISSUE THREAD

**Issue by HPMSGEN8** [BenjV/SYNO-packages#42]
Good Day

I upgraded to DSM 7, Used the new Package to repair and it is up and running BUT all MetaData is missing.

How do i copy the old ones over or what should i do here.

Thanks again & Happy Holidays

**Comment by BenjV** [comment]
Which package are you talking about and what metadata?

**Comment by HPMSGEN8** [comment]
I have backed up the whole folder before i did the repair. The DB loads that is not an issue the issue is just metadata that is missing like images etc...

**Comment by BenjV** [comment]
Those can be downloaded again from within Medusa with a mass update

**Comment by HPMSGEN8** [comment]
Thanks do i just use Mass Update and the Images ?

**Comment by HPMSGEN8** [comment]
Thanks issue resolved

**Comment by HPMSGEN8** [comment]
Sorted thanks
